### PR TITLE
Added ability to get weather status and see if its raining

### PR DESCRIPTION
**Pull request by mmarano25**
- Found weather library and signed up for API key.
- Note that the location is hardcoded to Irvine.
- weather_conditions.py under backend/data_collection/ provides two
functions to ascertain weather state:
    - get_status: returns a short string about the current weather e.g.
    Rain or Clear or Cloudy
    - is_okay_to_go_outside: currently returns True unless it's raining
    or snowing. We can consider other factors, but in the example of
    going for a run it seems too much up to individual preference.

### CODE REVIEW

**Comment by jessechong** [comment]
Awesome. Looks good to me.

**Comment by kajdreef** [comment]
I think looks good, should `pyowm` not be added to the requirements.txt? I haven't had the time to run it yet. Also how would the data come back to the phone? Because the weather is used to calculate the context (based on previous recommendations), will we have to fetch it from the server?

**Comment by mmarano25** [comment]
Yep! I’ll add pyowm to the requirements, forgot to do that. 

As far as getting it to the phone, I think if we want to do this we can add a weather/ GET route to the backend. This is more of a nice to have, especially this late, but it more integration may help sell the TA that weather is a source of data.

**Comment by kajdreef** [comment]
> As far as getting it to the phone, I think if we want to do this we can add a weather/ GET route to the backend.

I think it is something we need to have, else we can't do anything with the weather data right? We are going to create the context using previous recommendations. We pick the recommendations that have a similar situation (good/bad weather, high/low activity, time of day) and create the context (what someone likes to do) based on that.

Or did you have an other idea to use weather data?

**Comment by mmarano25** [comment]
I was under the impression that the backend would factor in the weather condition on what tasks to recommend rather than including weather in the context data.

If we wanted to include the weather in the context JSON the app produces, it would be pretty easy to make a GET route for it and just have the app ask for it on startup!

**Comment by mmarano25** [comment]
I can add the GET route while we figure out what to do.

**Comment by mmarano25** [comment]
Integrated docker refactor and added two GET routes, one for each function provided by the weather_conditions.py file.
`- Added "weather" GET route taking no parameters and returning a short
weather string e.g. "Rain" or "Clouds"
- Added "outside" GET route taking no parameters and returning a Boolean
value
- Both routes basically just return the value of the corresponding functions
from backend/server/data_collection/weather_conditions.py`

**Comment by kajdreef** [comment]
Looks good! I will merge it! 👍

**Pull request merged**
