### PR TITLE
Context

### PR DESCRIPTION
**Pull request by TDHTTTT**
@kajdreef Is it something you want for calculating the context?

### CODE REVIEW

**Comment by kajdreef** [comment]
I think we should also have an implementation of something that saves our own recommendations + weather + activity level and not only one json file with dummy data. What does the rest think?

**Comment by jessechong** [comment]
@kajdreef 

Yes. But the purpose of this is just to provide dummy data right? Of course we will keep track of what was recommended. I am not sure if we would care to keep track of the weather + activity level. I think just keeping track of what TASKS were recommended makes the most sense. Especially since we're edging closer to the deadline.

**Comment by kajdreef** [comment]
> Yes. But the purpose of this is just to provide dummy data right? 

Yes, but there is no way for me to read it at the moment and use it. It would be great if we can create pull requests that are fully integrated, so they can be used. 

>  I am not sure if we would care to keep track of the weather + activity level.

I think it is essential we keep track of weather + activity in combinatinon with what was recommended and if the user liked it or not. That is the context that the user is in, which gives us (hopefully) better results.

**Comment by TDHTTTT** [comment]
> > Yes. But the purpose of this is just to provide dummy data right?
> 
> Yes, but there is no way for me to read it at the moment and use it. It would be great if we can create pull requests that are fully integrated, so they can be used.

Why you can't read it & use it? Is there any missing information?

**Comment by kajdreef** [comment]
There is no function that allows us to use it by passing in weather and activity level. The data on its own seems fine, but it is not integrated with the rest. 

Also we need to add our own data as well, so store recommendations + feedback +activty data + weather.

**Comment by TDHTTTT** [comment]
Closed to reopen it to keep up with master

**Pull request closed without merging**
