### PR TITLE
Server now expects State and Context arguments

### PR DESCRIPTION
**Pull request by mmarano25**
- Added error handling as well when missing any argument
- Updated request_server.py with new test cases and correct query

### CODE REVIEW

**Comment by kajdreef** [comment]
@mmarano25 I will work on making sure the frontend uses the same format, so I will not merge it yet.

Also I saw that fetch (in javascript) doesn't allow you to send a json body to the server, because it violates RESTful architecture. Do we maybe need to change the setup to POST and send a json object with all the information? That will also require some changes on the backend.

**Comment by mmarano25** [comment]
Good to know that you can’t send a JSON over GET! I didn’t know that. I’ll revise the format and yes I think POST appears to be the way to go!

**Comment by kajdreef** [comment]
I think it is the design of fetch that doesn't allow it. The original author of REST said this about it:
> Yes. In other words, any HTTP request message is allowed to contain
a message body, and thus must parse messages with that in mind.
Server semantics for GET, however, are restricted such that a body,
if any, has no semantic meaning to the request. The requirements
on parsing are separate from the requirements on method semantics.
> So, yes, you can send a body with GET, and no, it is never useful
to do so.
>This is part of the layered design of HTTP/1.1 that will become
clear again once the spec is partitioned (work in progress).
> Roy Fielding (https://groups.yahoo.com/neo/groups/rest-discuss/conversations/messages/9962?guccounter=1)

So it is not the way to go, you can of course put everything in your URL, but that will not be the best way I think. Probably changing to post and retrieving the json is the best way (and nicest) way of doing it.

**Comment by kajdreef** [comment]
@mmarano25 Could you take a look at this? I changed a bunch of stuff but mainly it was focussed on:
1. Allowing us to send context, state, and number_of_resources through json to the server.
2. Send a JSON object back with ranked tasks and additional information
3. Rewriting the training data read function, because the data is now a JSON file instead of a csv file.

Please let me know if you have any questions and feel free to change stuff or fix bugs before you merge it. :)

**Comment by mmarano25** [comment]
Looks great to me @kajdreef ! 
I just pushed the database integration changes here.
The event table should now hold scraped events and is accessible through the get_db function in db.py, and I integrated your changes. Backend is looking pretty solid right now.

**Comment by mmarano25** [comment]
Oh yeah, logging now works correctly. Previously logging outside of main.py just disappeared and you had to print, but now logging is actually functional.
It should be more helpful than print in debugging because the module name will be listed next to the message!

**Comment by kajdreef** [comment]
Looks good! Everything seems to work well, so I am going to merge it!

**Pull request merged**
