### PR TITLE
Mental state questions

### PR DESCRIPTION
**Pull request by kajdreef**
Here a set of possible questions and follow up questions when we open the app. I don't think these are the final questions, but see them more as a starting point. Lets use this PR to discuss the questions. A few questions to start out: 
1. what is send to the backend?
2. What is the format that we are going to use to send the data? 
  - For example, will weather be categorized, or given a score?

### CODE REVIEW

**Comment by mmarano25** [comment]
As far as the format used to send the data, I think a JSON object of key-value pairs for each vector should work. 
Something like:
`{"State": {
    "sad": 4,
    "lonely": 2...
    }
 "Context": {
    "social": 1,
    "activity": 4"...
    }
}
`
could be sufficient to send the data.

**Comment by mmarano25** [comment]
For the questions, I think the initial questions are a good start. There might be a bit of overlap between anxious and stressed, but I think that it honestly might be good enough for what we're doing. \

One clarification: Are the `Context` questions going to be asked as a follow up to certain answers to the `State` questions? For example, if the user puts a 4 or higher for Stressed the system would additionally ask if the stress was centered around schoolwork?

**Comment by kajdreef** [comment]
> One clarification: Are the `Context` questions going to be asked as a follow up to certain answers to the `State` questions? For example, if the user puts a 4 or higher for Stressed the system would additionally ask if the stress was centered around schoolwork?

Yes, that is how I would imagine it.

Also I agree that the format should be a JSON-object of key value pairs.

**Comment by kajdreef** [comment]
I updated the description. Do @TDHTTTT and @jessechong have any feedback, else we can move forward with this in mind?

**Comment by jessechong** [comment]
To clarify, are the questions regarding context "On a scale to 1-5, how much do you agree with the following statements: School work has been stressful, Sleeping well, etc." factor into the provided data that is plugged into the back-end? The part that says "context JSON-object of key-value pairs based on interests and reactions on previous recommendations"?

Some thoughts:
1. State Json-Object
We currently provided sadness, loneliness, sleepiness, anxiousness, and stress. We should also include anger.
@mmarano25 I agree that anxiousness and stress have some overlap. I think that they are still distinct enough that we should consider both.

2. Context > Weather
I would instead enumerate weather in terms of temperature.
So, weather = "hot, warm, cold"
Hot: temperatures above 80 degrees
Warm: clear skies, 70-80
Cold: Cloudy, windy, rain, foggy, stormy, everything that isn't hot or warm.
Something like that.

3. Context > Activity
Activity should be low, moderate, or high.

4. Context > Events
I am assuming by "events" you mean how often the user goes out to events? I would replace events with "social_level"... or something like that. Events is a little too specific.

**Comment by TDHTTTT** [comment]
Are we going to ask a follow-up question for each state based questions? If not, how are we going to decide when to ask the follow-up question?

We are not going to discuss the tasks’ JSON-object here, right?

**Comment by kajdreef** [comment]
I will process the feedback tonight. 

> We are not going to discuss the tasks’ JSON-object here, right?

@TDHTTTT no, but it would be great. If you can open a PR with a draft so we can start working on it?

**Comment by TDHTTTT** [comment]
> 2. Context > Weather
>    I would instead enumerate weather in terms of temperature.
>    So, weather = "hot, warm, cold"
>    Hot: temperatures above 80 degrees
>    Warm: clear skies, 70-80
>    Cold: Cloudy, windy, rain, foggy, stormy, everything that isn't hot or warm.
>    Something like that.

I agree the value of weather should be more specific, but combining weather condition and tempreture together seems a bit vague (e.g. how about a hot rainy day?). So maybe we can have two separate weather related contex: “temperature”, ”weather condition”. Then we maybe able to use one-hot encoding for “weather condition”.

**Comment by TDHTTTT** [comment]
I am writing the description for Tasks, however, I am a bit unsure about the **context** part. Is it just determined by the previous reactions or the context now (i.e. if it is morning now)? If former is the case, how are we going the send the current context?

**Comment by kajdreef** [comment]
Both, as can be seen in the json example context contain current context (weather), but also personalized context (what does the person like to do under certain scenarios. That can be done using past responses to a certain task based on time of day.

Does that clarify it @TDHTTTT

**Comment by TDHTTTT** [comment]
> Both, as can be seen in the json example context contain current context (weather), but also personalized context (what does the person like to do under certain scenarios. That can be done using past responses to a certain task based on time of day.

But wouldn't a certain key in the json have ambiguity? For example, weather can both mean the current weather and if that person like that weather (time of the day seems similar).

**Comment by kajdreef** [comment]
I think that we should indeed change the context JSON object, I think time of day/weather/activity should inform the types of tasks the person likes to do, for example the weather is nice, and time of day is afternoon. The context (--> maybe better word is preference), would be working out or events if they are outside.

How someone reacts on time of day or weather is very subjective, and I think we can use past responses with environmental data (time of day/weather) can help us make a context/preference JSON object that helps us rank the tasks better. 

Ultimately, what I think the two objects need to represent it State informs what is relevant (helps us search), and context (or preference) is what helps us rank the search results in a way that makes sense for the user.

**Comment by jessechong** [comment]
> Ultimately, what I think the two objects need to represent it State informs what is relevant (helps us search), and context (or preference) is what helps us rank the search results in a way that makes sense for the user.

Yes!!

**Comment by kajdreef** [comment]
I think it is pretty good now! There are a few things to figure out:
1. How do we determine if a task was good or not, so we can use it in the future for personalization (context)?
2. We need to figure out a way to quantify the past responses. Maybe just a simple equation, but we do need to make something. This can maybe be done in a subsequent PR?

**Comment by mmarano25** [comment]
I agree with that Kaj! When I get a chance I’ll implement this in the request route.

**Comment by TDHTTTT** [comment]
> > Ultimately, what I think the two objects need to represent it State informs what is relevant (helps us search), and context (or preference) is what helps us rank the search results in a way that makes sense for the user.
> 
> Yes!!

I agree. how about we the use (mood) **state** + (current) **context** (current weather/current time of the day) and use it to search, leaving just **preference** for ranking. 

Also, I am not sure why you change the scale from (0-5) for mood **state** to (0-1) **context**? @kajdreef
Also, for categorical variables in **preference** part, I propose to use a n-vector to denote how much a person likes a certain category to encode more information. (more on this below). We do not need to do that for context since we are quite confident about the current **context** (e.g. what time is it now).

An example: (I kept the scales consistent)
```json
{
	"state": {
		"sadness": 0.0,
		"lonelyness": 5.0,
		"sleepyness": 4.0,
		"anxiousness": 1.0,
		"stress": 1.0
	},
	"context": {
		"time_of_day": "Morning",
		"sport": 0.0,
		"mindfulness": 0.0,
		"events": 0.0,
		"weather": "Good",
		"activity": "Low"
	},
	"preference": {
		"time_of_day": [4.0, 2.0, 5.0], //["Morning","Afternoon","Night"]
		"sport": 5.0,
		"mindfulness": 1.0,
		"events": 4.0,
		"weather": [1.0, 5.0, 1.0], //["Hot",", "Warm", "Cold"]
		"activity": [5.0, 4.0, 0.5] //["Low","Moderate","High"]
	}
}
```
##### Interpretation:
A sleepy person felt lonely in the morning. The weather is good and the current activity level is low (nothing much happened). Also, there is not much sport, mindfulness and events going on until now (I don't know what it means lol). 
...(We send the information(state+context) above to the backend and get a list of tasks back.)
...(We then rank those tasks according to preference, for that particular user, it would be:)
That person loves morning&night and had no strong preference about doing things in afternoon. The person loves sport and activities but not mindfulness. Only warm weather attracts that person. And the person likes to do things when the activity level is low or moderate, but wants to do absolutely nothing if it already had been a busy day.

**Comment by kajdreef** [comment]
>Also, I am not sure why you change the scale from (0-5) for mood state to (0-1) context? 

There is not a particular reason, 0-5 for state was chosen as a simple way to get input from the user. I used 0-1 for the others for two reasons: (1) to make a distinction that the data we collect for the state is not the same as context, and (2) we don't know how to calculate context yet, so a value between 0-1 seems okay to me. Could also have been 0-100, or pick any random range. 

> We send the information(state+context) above to the backend and get a list of tasks back

Just to elaborate, we send the state + context, however, only the state is used to get a list of tasks. However, then the context (or how I have been calling it preference) is used to rank them. 

> We then rank those tasks according to preference

I am not sure if I agree here. Yes, we rank the tasks according to the current context (or preferences based on this time of day).
```
"context": {
	"sport": 1.0,
	"mindfulness": 1.0,
	"events": 1.0,
	"activity": "Low"
}
```
However, you suggest sending current preferences and general preferences. Does the second one not encapsulate the first? 

I think that adding general preferences to it, could be interesting, however, I think it is better (and more accurate) to send the most up to date info which is the current context(aka preferences) and state. I think we should focus on recommending things for in the moment. 

Also as a note, (current) context (or preferences) is calculated the moment the person opens the app on the phone. That is why we don't send weather or time of day to the backend, because that that is already used to calculate the context (aka preferences).

**Comment by TDHTTTT** [comment]
@kajdreef  Maybe I was not clear. The current context and preference in my description are two things. The first one is the objective current condition and the second is subjective preference. We send mood state + current context to get back a list of activities and use preference to rank them. 

As for how to get those information, I think we can use scrapers/follow up question to determine the current context and feedback questions to determine the preference.

**Comment by TDHTTTT** [comment]
@kajdreef  I read your update in the README.md and it seems to me that the context you mean is the current context + preference I have.

**Comment by kajdreef** [comment]
The sport, mindfulness scores in preferences are initialized using a questionnaire, but after that it will change over time using their responses to certain recommendations. 

So first time the person likes everything, but it is morning and the person has not done anything so the initial context is:

```
{
	"sport": 1.0,
	"mindfulness": 1.0,
	"social": 1.0,
	"activity": "Low"
}
```

However, after 10 times recommending to workout in the morning and giving feedback not liking it the context becomes:
{
	"sport": 0.5,
	"mindfulness": 1.0,
	"social": 1.0,
	"activity": "Low"
}
```
So now it starts to give priority to other things like social events or mindfulness. But again ONLY state is used to get a set of tasks, and context is used to rank them.

**Comment by kajdreef** [comment]
> The main conflict we have now I guess would be if we are going to send the objective information (time_of_day [Morning, Afternoon, Night] Weather [Bad, Medium, Good]) to the backend. I think we should because that would probably keep the list sent back to the phone small and more accurate. 

@TDHTTTT I don't agree, I think that the backend should get the state and preferences which in my opinion contains the set of labels that we label the tasks with. Weather and time of day are used to compute the preferences for each label.
For example, if the time of day is morning and it is beautiful weather then sport is maybe high, while mindfulness is lower. We don't need to send more, I think.

I think the bigger discussion should be what are set of labels are, but those depend on the tasks.

**Comment by kajdreef** [comment]
Can you two weigh-in @mmarano25 @jessechong as well? :) Hopefully we can finalize it tonight, merge it, and start implementing it soon.

**Comment by mmarano25** [comment]
On mobile so I can’t contribute too much right now—

From what I can tell, it appears that the idea of keeping it constrained to one State vector and one Preference vector keeps it simple and I’d go with that. 

I would agree with Tony that a third vector to reflect the absolute now would be nice—maybe if we collected more data like activity level or diet than we could tell that more accurately, but I think for the data we have now we can capture the user well enough in two objects that a third seems like too much for me, especially with the rapidly approaching due date.

**Comment by mmarano25** [comment]
I think in the interest of time let's go with just the two objects. I've opened a pull request updating the backend and test file to use the two JSON objects as queries.

**Comment by jessechong** [comment]
I agree with what Kaj said, in general.
State -> to query database and retrieve tasks
Context -> to rank them.

Context is the user's _current_ "preferences".

> "However, after 10 times recommending to workout in the morning and giving feedback not liking it the context becomes something different" - Kaj

> "I think in the interest of time let's go with just the two objects. I've opened a pull request updating the backend and test file to use the two JSON objects as queries."

Sounds good Matt. I'm not sure how to handle pull requests and I'm afraid I might destroy our master branch so please someone else approve it ;) ..... The code looks fine to me

**Comment by kajdreef** [comment]
Okay! I am going to merge it now!

**Pull request merged**
