### PR TITLE
First version of a web scraper that scrapes the ARC site

### PR DESCRIPTION
**Pull request by kajdreef**
First version of web scraper. At the moment it looks at [this page](https://www.campusrec.uci.edu/groupx/index.asp) and scrape its schedule and create a dictionary which holds for each day a dictionary where the key is the time and the value is a list of classes at that time. For example:

```json
{
        "Monday": {"1030": ["F45", "Zumba"]},
        "Tuesday":{"1030": ["F45", "Zumba"]},
        "Wednesday": {"1030": ["F45", "Zumba"]},
        "Thursday": {"1030": ["F45", "Zumba"]},
        "Friday": {"1030": ["F45", "Zumba"]},
        "Saturday": {"1030": ["F45", "Zumba"]},
        "Sunday": {"1030": ["F45", "Zumba"]},
}
```

It has not yet been implemented with the server, because I am not sure if this is the best way to go, or if it should scrape every morning for example the website.

Feedback or changes would be welcome.

### CODE REVIEW

**Comment by mmarano25** [comment]
I like how this looks! 

I'm going to put some work into setting up the database today, and hopefully that will help us figure out how this fits in the current repository.

**Comment by mmarano25** [comment]
I think if we wanted to do more work on the scraper the next steps would be categorization of each event, but I'm not sure how robust our recommendation of events should be.

Are we intending to personalize event recommendation or just to show upcoming events?

**Comment by kajdreef** [comment]
I was thinking that the front end could maybe look something like this for example:

--------------------------------
|  Go to a event:
|    upcoming events:
|        - 10:00 F45
|        - 10:30 Zumba
--------------------------------

So if the recommendation is go to an event or go workout we could pull additional information to enrich the view.

**Comment by mmarano25** [comment]
That makes sense to me! And then the type of task ARC Event might have for example a social and fitness tag?

**Comment by kajdreef** [comment]
> the type of task ARC Event might have for example a social and fitness tag?

Yes, I think so. Also the ARC events that are scraped here are Group Lessons, so I would say we can tag them both as social and fitness.

**Comment by jessechong** [comment]
To address your question, I think that the calendar should be scraped every morning. 
Definitely support the "enrich the view" idea. Will consider this when designing the front-end.

On a side note, that calendar is rich in information. There seems to be 4 different types of passes. Should our app at all indicate that you need a pass to attend the event? In some way, we would be advertising Campus Recreation, but I think that it is important for the user to know that they have to pay before attending an event (especially if MESA targets a UCI student audience...)

**Comment by kajdreef** [comment]
>I think that the calendar should be scraped every morning.

I agree, I will look into using [this](https://apscheduler.readthedocs.io/en/latest/), it allows you to schedule certain function calls. If we would call the setup for this when we start the server (like how @mmarano25 implemented the training phase of the model) then it should be pretty simple to schedule our scraper.

> 4 different types of passes
Yes, 1 pass for F45, 1 pass for Yoga, 1 pass for Group X, and one all access. We could scrape it separately and add info to the returned task saying: we recommend class: F45 (note: need all access pass or the F45 pass). However, it wouldn't say this is a need to have, but more a nice to have.

**Comment by kajdreef** [comment]
Added the feature that the scraper is scheduled every morning, but it will at least run once before the first request. Now it needs to be combined with ranking/recommendation.

I think it is ready to merge. I will open an issue to remind us to add additional information to the web scraper, like subscriptions are needed etc.

**Comment by mmarano25** [comment]
Looks good to me! I'll approve this, and then I should be able to integrate it with the database to just have it go straight into the Events table

**Pull request merged**
