### PR TITLE
updated definition for tasks

### PR DESCRIPTION
**Pull request by TDHTTTT**

### CODE REVIEW

**Comment by kajdreef** [comment]
I like the definitions where you start out with. However, for the task is only determined by the state of the user. And the ranking of the tasks are determined by context. So when defining tasks I think we only have to state:
1. task name
2. example states
3. set of labels describing the tasks 

example:
```
{
    "yoga" : {
        "labels": ["workout", "social"],
        "states": [
            {
                "sadness": 3.0,
                "lonelyness": 1.0,
                "sleepyness": 1.0,
                "anxiousness": 4.0,
                "stress": 5.0
            }, 
            {
                "sadness": 0.0,
                "lonelyness": 4.0,
                "sleepyness": 0.0,
                "anxiousness": 4.0,
                "stress": 4.0
            }
        ]
    }
}
```

So to further clarify the process of matching and ranking of the tasks 
1. We have a multi dimensional data set, because we have state of user, time of day, preferences , and finally tasks.
2. So we use pre-filtering to reduce the data to only what is necessary in that moment (remove all irrelevant data).
3. We leave out the context (preferences) and only use the state of the user and items to do our matching.
4. we use post filtering to rank our recommendations based on the preferences of the user. 

(pre/post filtering are known methods for using context in recommendations, see slides 57 and 58 of T7  )

So what I think we need here is: 
- Definition of *task* [**DONE**]
- Definition of *state* [**DONE**]
- A set of Labels to be used by the user for in preferences at the moment we have: *sport*, *mindfulness*, *social*, and *activity*. Are there more necessary?
- Define format of how to present tasks
- A set of tasks with a few example states that it could be useful for, meaning in which state(s) could this be useful? 
- (Maybe a separate (json?) file where we can add new tasks?)

@jessechong @mmarano25 What do you all think? Also lets brain storm about tasks when we have the format down? Maybe just PR for each new task that we think of to a task.json file?

**Comment by jessechong** [comment]
> A set of Labels to be used by the user for in preferences at the moment we have: sport, mindfulness, social, and activity. Are there more necessary?

What is "activity"? I think the three tags mentioned "Sport, mindfulness, and social" are sufficient for this app.

By the way, these labels apply to EVENTS also right? Not just TASKS?
This is how I see it:
Sport Task -> run, pushups
Mindfulness Task  -> Meditation, introspection
Social Task -> Talk to a friend, talk to somebody
Activity Task -> ?

Sport Event -> ARC Yoga, ARC rock climbing
Mindfulness Event -> Visit UCI counselor
Social Event -> UCI Anteater Involvement Day
Activity Event -> ??

> Define format of how to present tasks
Discuss in my PR so we can keep it all in the same place. This concerns the UI:  https://github.com/TDHTTTT/MESA/pull/15


> A set of tasks with a few example states that it could be useful for, meaning in which state(s) could this be useful?
> (Maybe a separate (json?) file where we can add new tasks?)

Can you clarify on these two points? I don't understand.

**Comment by kajdreef** [comment]
> What is "activity"? I think the three tags mentioned "Sport, mindfulness, and social" are sufficient for this app.

I agree, lets keep for labels at the moment:
1. Sport
2. Mindfulness
3. Social

Maybe only an additional label to say if it indoor or outdoor?
4. Outdoor/Indoor

>By the way, these labels apply to EVENTS also right? Not just TASKS?

I agree.

> Define format of how to present tasks

I just meant to state here that we need to figure out a common format for each task that we think of. This in mind with what information need to be presented to the user. For example, the format can be:

```json
{
    "task_1" : {
        "description": "",
        "labels": ["label1", "label2"],
        "states": [{},{},{}]
    },
    "task_1" : {
        "description": "",
        "labels": ["label1", "label2"],
        "states": [{},{},{}]
    }
}
```

The file would be a json file for example named: tasks.json. When we start up the server we load the data into the database and use the tasks' states to train our recommendation model. Having a format for the data helps us to make sure that we have for all the tasks the same information.

> A set of tasks with a few example states that it could be useful for, meaning in which state(s) could this be useful?

This is just necessary to train a machine learning model. To train a model we need a set of tasks and for each task a set of example states in which we would use that specific task. Without that we can not train the model well.

**Comment by jessechong** [comment]
@kajdreef 

Sure did. It is difficult to keep track of what our definitions of STATE, CONTEXT, and LABELS are since we keep refining them.

**Comment by TDHTTTT** [comment]
Close this PR since we have decided on the definition

**Pull request closed without merging**
