### PR TITLE
Personalize

### PR DESCRIPTION
**Pull request by TDHTTTT**
Updated personalize formula

### CODE REVIEW

**Comment by jessechong** [comment]
Looks good!

`ranking.py`
Are the tasks returned in `rank_tasks` sorted by highest score to lowest? From what I can tell it seems like its not. 

`return _sigmoid(weight*probability) - 0.5`
The `-0.5` is so that the score is always between -0.5 and 0.5, yes?

**Comment by TDHTTTT** [comment]
> `return _sigmoid(weight*probability) - 0.5`
> The `-0.5` is so that the score is always between -0.5 and 0.5, yes?

The score/probability will be (0,1).

"""json
{
  "task1": {
    "name": "Running",
    "prob": 0.3807970779778823
  },
  "task2": {
    "name": "yoga",
    "prob": 0.0
  },
  "task3": {
    "name": "Go to event",
    "prob": 0.0
  }
}
"""

**Comment by TDHTTTT** [comment]
One other thing to notice is that although json can preserve the order of the elements, here I didn't return an ordered list/array for tasks. Instead, I attached the probability to the tasks and send it to the frontend, hoping that frontend could do sorting using the probability.

I could certainly hide that complexity at my level by return an ordered list/array and hide the probability. What do you want for frontend? @jessechong

**Comment by kajdreef** [comment]
I think the order should be based on key. For example, at the moment the client asks for 3 tasks. The value associated with "task1" should have the highest probability, "task2" the second highest, and 'task3" the lowest. Then the client doesn't have to do any ranking or sorting any more, but only assign the tasks to the right task UI element using the correct key (ie, the "task1" for the first task, "task2" for the second task, etc.).

**Comment by kajdreef** [comment]
My suggestion for returning to the frontend would be something along this line:

```
{
  "task1": {
    "name": "Running",
    "description": "describing task 1",
    "event_data": {}
  },
  "task2": {
    "name": "yoga",
    "description": "describing task 2",
    "event_data": {}
  },
  "task3": {
    "name": "Go to event",
    "description": "describing task 2",
    "event_data": {
        "place": "Location Name",
        "event_name": "Some Fun Event",
        "time": "19:00-21:00"
        "description": "Have some fun!"
    }
  }
}
```

For now, you could leave `event_data` empty, by just returning an empty json object (= `{}`).

**Comment by TDHTTTT** [comment]
> For now, you could leave `event_data` empty, by just returning an empty json object (= `{}`).

That would be the events we scraped, right? @kajdreef

**Comment by TDHTTTT** [comment]
This is what I think simplest:
```json
[
  {
    "description": "Take your running shoes out of the closest and go for a run!",
    "event_data": {},
    "name": "Running"
  },
  {
    "description": "",
    "event_data": {},
    "name": "Go to event"
  },
  {
    "description": "Go do some Yoga exercises to empty your mind!",
    "event_data": {},
    "name": "yoga"
  }
]
```
The order is preserved in the json and the most likely task appears on the top. I omitted the "TaskN" to be more concise.  @kajdreef

**Comment by kajdreef** [comment]
Looks good! So I have merged it! 👍

**Pull request merged**
